spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.84.18.178:3306/temi?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    hibernate:
        ddl-auto: update
        generate-ddl: true
server:
  port: 3000